const jsonBLCAsignature = {
        "psi_r3_v9_vs_others": "R3-V9",
        "psi_r2_v25_vs_others": "R2-V25",
        "psi_asian_vs_others": "R2-V26 (Asian)",
        "psi_r2_v27_vs_others": "R2-V27 (Luminal mRNA)",
        "psi_fgfr3_mut_vs_others": "R1-V2 (Mut-FGFR3_Luminal_papillary mRNA)",
        "psi_r2_v16_vs_others": "R2-V16",
        "psi_r3_v19_vs_others": "R3-V19",
        "psi_kras_mut_vs_others": "R2-V19 (Mut-KRAS)",
        "psi_r2_v22_vs_others": "R2-V22",
        "psi_r2_v15_vs_others": "R2-V15",
        "psi_r3_v7_vs_others": "R3-V7",
        "psi_r2_v6_vs_others": "R2-V6",
        "psi_tp53_mut_vs_others": "R1-V1 (Poor Survival_Mut-TP53_Basal_squamous mRNA)",
        "psi_rbm10_mutpositive_sox4_amp_vs_others": "psi_rbm10_mutpositive_sox4_amp_vs_others",
        "psi_r2_v1_vs_others": "R2-V1",
        "psi_r2_v4_vs_others": "R2-V4",
        "psi_r3_v26_vs_others": "R3-V26 (tissue source CF)",
        "psi_r2_v11_vs_others": "R2-V11 (Luminal_papillary mRNA)",
        "psi_r3_v21_vs_others": "R3-V21",
        "psi_r2_v20_vs_others": "R2-V20",
        "psi_rbm10_mut_vs_others": "R2-V10 (Poor Survival_Mut-RBM10_miRNA 4)",
        "psi_r3_v5_vs_others": "R3-V5",
        "psi_sox4_amppositive_tp53_mut_vs_others": "psi_sox4_amppositive_tp53_mut_vs_others",
        "psi_pde4d_del_vs_others": "R2-V24 (Del-PDE4D)",
        "psi_noninvasive_blca_history_vs_others": "R2-V28 (Noninvasive_BLCA_history)",
        "psi_cdkn2a_delpositive_fgfr3_mut_vs_others": "psi_cdkn2a_delpositive_fgfr3_mut_vs_others",
        "psi_r2_v21_vs_others": "R2-V21",
        "psi_r2_v2_vs_others": "R2-V2",
        "psi_r2_v13_vs_others": "R2-V13 (Poor Survival_Neuronal mRNA)",
        "psi_r2_v3_vs_others": "R2-V3",
        "psi_r3_v6_vs_others": "R3-V6 (Mut-SF1)",
        "psi_r2_v18_vs_others": "R2-V18",
        "psi_r2_v17_vs_others": "R2-V17",
        "psi_r2_v9_vs_others": "R2-V9"
}
export default jsonBLCAsignature;